version: 0.2

env:
  parameter-store:
    USERNAME: /dockerhub/username
    PASSWORD: /dockerhub/password

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - node --version
      - echo "Node.js installed"
      
  pre_build:
    commands:
      - npm install
      - echo "Dependencies installed"
      
  build:
    commands:
      - docker build . -t sathya1101/netflix-clone:latest
      - echo "Docker image built successfully"
      
  post_build:
    commands:
      - echo "Logging into DockerHub"
      - docker login -u $USERNAME -p $PASSWORD
      - docker push sathya1101/netflix-clone:latest
      - echo "Image pushed to DockerHub"

artifacts:
  files:
    - '**/*'
